# Generated by Django 4.0 on 2021-12-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_actors_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='movies',
            field=models.ManyToManyField(related_name='movies', to='movies.Movies'),
        ),
    ]
